## server
server:
  port: 8080
  servlet:
    context-path: /api
  tomcat:
    mbeanregistry:
      enabled: on

## actuator
management:
  info:
    java:
      enabled: on
    env:
      enabled: on
    os:
      enabled: on
  endpoints:
    web:
      exposure:
        include: "*"

## spring
spring:
  application:
    name: study-spring-ai
  main:
    banner-mode: log
    allow-bean-definition-overriding: on
  data:
    redis:
      repositories:
        enabled: off
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${database_host:localhost:5432}/${database_name:study_spring_ai}
    username: ${database_username}
    password: ${database_password}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_batch_fetch_size: 100
        discriminator:
          ignore_explicit_for_joined: on
  threads:
    virtual:
      enabled: on
  ai:
    openai:
      api-key: ${openai_api_key}

## malgn
malgn:
  enabled: on
  auth:
    user:
      enabled: off
      host: ${auth-user-host:http://localhost:8080}
  redis:
    enabled: off
    host: ${redis_host:redis://localhost:6379}
  notification:
    enabled: off
    host: ${notification_host:http://localhost:8080}

## logging
logging:
  charset:
    console: UTF-8
    file: UTF-8
  file:
    name: ${logs_path}/${spring.application.name}.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} ${LOG_LEVEL_PATTERN:%-5p} ${PID} --- [%15.15t] %-40.40logger{39} :%06L : %m%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} ${LOG_LEVEL_PATTERN:%-5p} ${PID} --- [%15.15t] %-40.40logger{39} :%06L : %m%n"
  logback:
    rollingpolicy:
      file-name-pattern: "${logs_path}/%d{yyyy-MM-dd}/${spring.application.name}.%d{yyyy-MM-dd}.%i.log"
      max-file-size: 10MB
      max-history: ${log_max_history:10}
  level:
    root: info
    web: ${logs_level:info}
    org.bobpark: ${logs_level:info}